// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: nodecom.proto
#ifndef GRPC_nodecom_2eproto__INCLUDED
#define GRPC_nodecom_2eproto__INCLUDED

#include "nodecom.pb.h"

#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace nodecom {

class NodeCom final {
 public:
  static constexpr char const* service_full_name() {
    return "nodecom.NodeCom";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status SubmitNonce(::grpc::ClientContext* context, const ::nodecom::SubmitNonceRequest& request, ::nodecom::SubmitNonceReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::nodecom::SubmitNonceReply>> AsyncSubmitNonce(::grpc::ClientContext* context, const ::nodecom::SubmitNonceRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::nodecom::SubmitNonceReply>>(AsyncSubmitNonceRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::nodecom::SubmitNonceReply>> PrepareAsyncSubmitNonce(::grpc::ClientContext* context, const ::nodecom::SubmitNonceRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::nodecom::SubmitNonceReply>>(PrepareAsyncSubmitNonceRaw(context, request, cq));
    }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::nodecom::SubmitNonceReply>* AsyncSubmitNonceRaw(::grpc::ClientContext* context, const ::nodecom::SubmitNonceRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::nodecom::SubmitNonceReply>* PrepareAsyncSubmitNonceRaw(::grpc::ClientContext* context, const ::nodecom::SubmitNonceRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status SubmitNonce(::grpc::ClientContext* context, const ::nodecom::SubmitNonceRequest& request, ::nodecom::SubmitNonceReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::nodecom::SubmitNonceReply>> AsyncSubmitNonce(::grpc::ClientContext* context, const ::nodecom::SubmitNonceRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::nodecom::SubmitNonceReply>>(AsyncSubmitNonceRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::nodecom::SubmitNonceReply>> PrepareAsyncSubmitNonce(::grpc::ClientContext* context, const ::nodecom::SubmitNonceRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::nodecom::SubmitNonceReply>>(PrepareAsyncSubmitNonceRaw(context, request, cq));
    }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientAsyncResponseReader< ::nodecom::SubmitNonceReply>* AsyncSubmitNonceRaw(::grpc::ClientContext* context, const ::nodecom::SubmitNonceRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::nodecom::SubmitNonceReply>* PrepareAsyncSubmitNonceRaw(::grpc::ClientContext* context, const ::nodecom::SubmitNonceRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_SubmitNonce_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status SubmitNonce(::grpc::ServerContext* context, const ::nodecom::SubmitNonceRequest* request, ::nodecom::SubmitNonceReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_SubmitNonce : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_SubmitNonce() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_SubmitNonce() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SubmitNonce(::grpc::ServerContext* context, const ::nodecom::SubmitNonceRequest* request, ::nodecom::SubmitNonceReply* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSubmitNonce(::grpc::ServerContext* context, ::nodecom::SubmitNonceRequest* request, ::grpc::ServerAsyncResponseWriter< ::nodecom::SubmitNonceReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_SubmitNonce<Service > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_SubmitNonce : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_SubmitNonce() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_SubmitNonce() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SubmitNonce(::grpc::ServerContext* context, const ::nodecom::SubmitNonceRequest* request, ::nodecom::SubmitNonceReply* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SubmitNonce : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_SubmitNonce() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::nodecom::SubmitNonceRequest, ::nodecom::SubmitNonceReply>(std::bind(&WithStreamedUnaryMethod_SubmitNonce<BaseClass>::StreamedSubmitNonce, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_SubmitNonce() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SubmitNonce(::grpc::ServerContext* context, const ::nodecom::SubmitNonceRequest* request, ::nodecom::SubmitNonceReply* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSubmitNonce(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::nodecom::SubmitNonceRequest,::nodecom::SubmitNonceReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_SubmitNonce<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_SubmitNonce<Service > StreamedService;
};

}  // namespace nodecom


#endif  // GRPC_nodecom_2eproto__INCLUDED
